config/routes.rb
RentalBookinsApp::Application.routes.draw do

  resources :properties do
    resources :bookings
  end

  root :to => "dashboard#index"

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :guest_name, :check_in_date, :check_out_date
  
  belongs_to :property
  
  default_scope :order => 'bookings.created_at ASC'
end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :name
  
  has_many :bookings #, :dependent => destory
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def index
    @property = Property.find(params[:property_id])
    @title = @property.name
    @breadcrumb = { :name => "Back to Dashboard", :path => root_path }
    @navigation = "property"
    @sidebar = "bookings"
    @bookings = @property.bookings
  end
  
  def new
    @navigation = "property"
    @property = Property.find(params[:property_id])
    @booking = Booking.new
  end

  def create
    @property = Property.find(params[:property_id])
    @booking = @property.bookings.build(params[:booking])
    if @booking.save
      flash[:success] = "Booking created"
      redirect_to [@property, @booking]
    else
      @navigation = "property"
      render 'new'
    end
  end

  def show
    @property = Property.find(params[:property_id])
    @booking = Booking.find(params[:id])
    @title = @property.name
    @breadcrumb = { :name => "Back to Dashboard", :path => root_path }
    @navigation = "property"
    @sidebar = "bookings"
    @bookings = @property.bookings
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def index
    @navigation = "dashboard"
    @sidebar = "properties"
    @properties = Property.all
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  
  def new
    @navigation = "dashboard"
    @property = Property.new
  end

  def create
    @property = Property.new(params[:property])
    if @property.save
      flash[:success] = "Property created"
      redirect_to @property
    else
      @navigation = "dashboard"
      render 'new'
    end
  end
  
  def show
    @property = Property.find(params[:id])
    @title = @property.name
    @breadcrumb = { :name => "Back to Dashboard", :path => root_path }
    @navigation = "property"
    @sidebar = "bookings"
    @bookings = @property.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/bookings/_booking.html.erb
<li><%= link_to booking.guest_name, [@property, booking] %></li>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<h1>Create New Booking</h1>
<hr />
<%= form_for [@property, @booking] do |f| %>
	<div class="field">
		<%= f.label :guest_name %><br />
		<%= f.text_field :guest_name %>
	</div>
	<div class="field">
		<%= f.label :check_in_date %><br />
		<%= f.text_field :check_in_date %>
	</div>
	<div class="field">
		<%= f.label :check_out_date %><br />
		<%= f.text_field :check_out_date %>
	</div>
	<hr />
	<div class="actions">
		<%= f.submit "Create this booking" %> or <%= link_to "Cancel", property_path(@property) %>
	</div>
<% end %>

app/views/bookings/show.html.erb
<h1><%= @booking.guest_name %></h1>
<ul>
	<li>Check-in <%= @booking.check_in_date %></li>
	<li>Check-out <%= @booking.check_out_date %></li>
</ul>	

app/views/dashboard/index.html.erb
<% if @properties.empty? %>
<div class="welcome_message">
	<div>Welcome to your Really Simple Rental Bookings application.</div>
	<div>Create your first property <%= link_to "Add Property", new_property_path %></div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="span-24">
	<nav>
		<ul>
			<li><%= link_to "About", '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="span-24">
	<% if @breadcrumb %>
	<div id="breadcrumb">
	    <%= link_to @breadcrumb[:name], @breadcrumb[:path] %>
	</div>
	<% end %>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Sign in", '#' %></li>
		</ul>
	</nav>
</header>

app/views/layouts/_navigation.html.erb
<h1><%= @title ? @title : @navigation.titleize %></h1>
<nav class="span-16">
	<%= render "layouts/navigation/" + @navigation %>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
	<% if @sidebar %>
	<h1><%= @sidebar.titleize %></h1>
	<%= render "layouts/sidebars/" + @sidebar %>
	<% end %>
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen, projection' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'blueprint/plugins/fancy-type/screen', :media => 'screen, projection' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen, projection' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Really Simple Rental Bookings</title>
  <%= javascript_include_tag :defaults %>
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>
		<section class="span-24">
			<% flash.each do |key, value| %>
			  <%= content_tag(:div, value, :class => "flash #{key}") %>
			<% end %>
			<%= render 'layouts/navigation' %>
		</section>
		<section class="span-16 border">
			<hr />
			<%= yield %>
		</section>
		<section class="span-8 last">
			<%= render 'layouts/sidebar' %>
		</section>
		<%= render 'layouts/footer' %>
		<% if Rails.env.development? %>
		<section class="span-24">
			<%= debug(params) %>
		</section>
		<% end %>
	</div>
</body>
</html>

app/views/layouts/navigation/_dashboard.html.erb
<ul>
	<li><%= link_to "Dashboard", root_path %></li>
	<li><%= link_to "Guests", '#' %></li>
	<li><%= link_to "Templates", '#', :class => "float" %></li>
</ul>

app/views/layouts/navigation/_property.html.erb
<ul>
	<li><%= link_to "Overview", property_path(@property) %></li>
	<li><%= link_to "Bookings", property_bookings_path(@property) %></li>
</ul>

app/views/layouts/sidebars/_bookings.html.erb
<%= link_to "Add Booking", new_property_booking_path(@property), :class => "button" %>
<%= render @bookings %>

app/views/layouts/sidebars/_properties.html.erb
<%= link_to "Add Property", new_property_path, :class => "button" %>
<%= render @properties %>

app/views/properties/_property.html.erb
<li><%= link_to property.name, property %></li>

app/views/properties/new.html.erb
<h1>Create New Property</h1>
<hr />
<%= form_for(@property) do |f| %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<hr />
	<div class="actions">
		<%= f.submit "Create this property" %> or <%= link_to "Cancel", root_path %>
	</div>
<% end %>

app/views/properties/show.html.erb
<% if @bookings.empty? %>
<div class="welcome_message">
	<div>Getting Started</div>
	<div>Create your first booking <%= link_to "Add Booking", new_property_booking_path(@property) %></div>
</div>
<% end %>